### ISSUE TITLE
mining with i9 7980XE ( 18 cores)

### ISSUE THREAD

**Issue by Avidlearner13** [arionum/miner#3]
Today i got this CPU and I keep getting these errors no matter now many cpus I choose from config. Or which instruction I choose. I keep on getting this error of cpu 34 even though i am asking not to use more than 18 cpus.

![captureerror](https://user-images.githubusercontent.com/19258637/36393969-a0048da2-1577-11e8-82f7-f723a15556bb.JPG)

**Comment by ProgrammerDan** [comment]
I believe we were in touch in discord, I gave you an affinity-free version that worked, although slower.

**Comment by Avidlearner13** [comment]
yeah thanks. Finally just returned the CPU. not worth the cores.

**Comment by ProgrammerDan** [comment]
Probably should close regardless, since on wrong repo -- hopefully we can have more success on future machines.
